### ISSUE TITLE
Error. Failed streamer get

### ISSUE THREAD

**Issue by ProtostarMusic** [Nifty255/Bit-Boss-Battles#1]
Hey, today i started getting this issue. It was working fine last week and ive even cleared cookies/cleared auth from within twitch itself and re-authed but to no avail.

My twitch username is protostar if that would help.

Kind regards

**Comment by Nifty255** [comment]
This was due to a change in the Twitch API which prevented the widget from obtaining a streamer's Twitch ID (different from username or display name). Fixed by commit b3b4a47b76371c3386ca15299a0e6e8ce898d718
