### ISSUE TITLE
ERROR. FAILED STREAMER GET.

### ISSUE THREAD

**Issue by Brrrt** [Nifty255/Bit-Boss-Battles#13]
Hi! I get the following error when trying to use the Bit boss battle plugin: 

ERROR. FAILED STREAMER GET.

It worked fine before and am wondering if I need to click something? 

User: Eswoogi

Thanks! 

All the best.

**Comment by Nifty255** [comment]
Twitch appears to have broken something in their API. I'm working on it now.

**Comment by Brrrt** [comment]
Amazing, thanks Nifty255, appreciate the update!
