### ISSUE TITLE
Error saving: Invalid ID

### ISSUE THREAD

**Issue by shadowpz** [Nifty255/Bit-Boss-Battles#16]
Hey, i luv ur app, awesome idea
ok so, every time i try to do any changes on my settings page i get Error saving: Invalid ID, then i go back to launcher and the url doesnt updates. so i can see the bbs on my obs just not with the settings i like.

But if i launch widget from the launcher website i can see the changes i want.

i tried hard reset, but still not working :(

maybe im doing something wrong but idk, it was working fine for a couple of days then it askd me on obs to update the url, and now i cant get it to work with the settings i like

**Comment by Nifty255** [comment]
Can you do me a favor and send me a DM on Twitter with the link you're shown on the Launcher page? Or just the ID the link is showing you here if you know where that is.

**Comment by Nifty255** [comment]
After reviewing your user ID, I've found your problem. BBB believes a user ID to be invalid if it's shorter than 6 digits or longer than 8. Yours has 9 for some reason. I'll update the code to begin accepting 9 digit user ID's in a moment...

**Comment by bwanatv** [comment]
Hi.  I encountered this issue today and my ID is 5 digits (12519).  Could you maybe update to support IDs of that length?
