### ISSUE TITLE
No Name / HP 

### ISSUE THREAD

**Issue by Brrrt** [Nifty255/Bit-Boss-Battles#17]
Hi Nifty! 

Hope you're well? 

Loving the new implementation of donations through stream labs.

I'm having issues getting any HP or names onto my boss at the moment though? 

Let me know if there's anything I need to do? I tried the hard reset but no resolve as of yet! 

Thanks Nifty. 

All the best

**Comment by Nifty255** [comment]
After the donations update, a number of users are experiencing the same issue. As I cannot reproduce the problem myself, I am in need of testing partners. If you're willing to help, please DM me on Twitter @Nifty255
