### ISSUE TITLE
Feedback/Feature Requests

### ISSUE THREAD

**Issue by Charionna** [Nifty255/Bit-Boss-Battles#2]
I've been using the app for two days and I love it so far. There are some ways I think the app can become even better than it is right now.

Let subscriptions/resubs affect the boss as well for an adjustable amount. If the current boss subs let it full heal them as well.

Rework overkill to allow a base HP + overkill. If someone overkills a boss by 500 bits, let me set a base hp (1000) and then add the overkill amount on top of the base hp (total 1500 instead of 500).

Allow customizable hp bar colors. This would simply make it easier for the app to blend in with already existing overlays.

Thanks for your work on the app, I would love to contribute in any way outside patreon if you have a link.

**Comment by Nifty255** [comment]
I'll be rewording these features into their own separate issues for organization. Thanks for your feedback!
