### ISSUE TITLE
name scrolling should take name length into account

### ISSUE THREAD

**Issue by Fire-** [Nifty255/Bit-Boss-Battles#21]
It looks like names will scroll in the widget even when they do not need to as they are not long enough to clip.

<img src="https://cloud.githubusercontent.com/assets/1456217/25301552/27809f42-26df-11e7-9801-c0da57825b6b.png" width="290px" alt="image" style="max-width:290px;" valign="middle"> -> <img valign="middle" src="https://cloud.githubusercontent.com/assets/1456217/25301551/2024ec4e-26df-11e7-9130-c4a269666195.png" width="290px" alt="image" style="max-width:290px">

This could be resolved by checking if the text element width exceeds the widget width before scrolling or shrinking the text to fit.

**Comment by Nifty255** [comment]
The widget DOES have a check for such instances. More than likely, since you are using a custom font, you haven't also changed the font of the invisible test span (span id="test") which is used to calculate the width of the username without interference from containers.
