### ISSUE TITLE
cant reset boss to previous

### ISSUE THREAD

**Issue by sparten9999** [Nifty255/Bit-Boss-Battles#22]
im fallowing the instructions on the help page and cant get the boss to change. the widget always goes back to myself and with full health

**Comment by kayosgirl** [comment]
I am also having this issue. I have copied the link into my browser and my source in OBS and I get the confirmation message and then when I go back and put my original link in it resets. If I just put the new boss link in a new tab in my browser and hide the source in obs and then close the tab and re enable the source in obs it still shows me. I feel like its something simple.

**Comment by Nifty255** [comment]
Firstly, placing the Set Boss link in one browser does not affect the other. Still, you claim to have placed it in both, so I'll look for an issue and fix if I find one.

**Comment by sparten9999** [comment]
yah i closed all windows and sources with bitboss open. put the reset link in. then it says to close it and reopen bitboss and it should be good. but always just full health my name

**Comment by Nifty255** [comment]
Try using BBB's Hard Reset link (found on the Launcher page) on both your browser and stream software, and follow those directions.

**Comment by sparten9999** [comment]
the hard reset also didnt fix help when i tried it
