### ISSUE TITLE
Running on your own server?

### ISSUE THREAD

**Issue by GIToez** [Nifty255/Bit-Boss-Battles#23]
How would be go about setting this up on our own webserver? I thought it be a little simple but unable to get twitch to auth with it./Would this work with the new affiliate program. Been keeping n eye on this for a while but haven't messed with it till i was partner but now.

**Comment by Nifty255** [comment]
This is neither a bug report nor a feature request. Please refrain from using the Issues to ask such questions. You're having trouble because you're not creating your own API clients for Twitch and Streamlabs. And yes it does work with the Affiliate program.
