### ISSUE TITLE
Persistent, overkill boss gets Max HP & HP reduced on reload

### ISSUE THREAD

**Issue by growf** [Nifty255/Bit-Boss-Battles#9]
There's a problem when the boss is set to be persistent, overkill is enabled, and the current boss managed to get more than the `Initial HP` value as their max health (due to a sufficiently large overkill).

The app doesn't store the current boss' max HP in a persistent cookie (just the _current_ HP). When the app is reloaded the boss' max HP gets set to `hpAmnt`, which for overkill is the value of `getCookie("hpinit", "")`, and their current HP gets limited to this value by the line:
```
prevHp = Math.min(parseInt(getCookie("currentHp", "0")), hpAmnt);
```

As a result things like [this](https://www.twitch.tv/videos/124069062) happen.

For overkill to work with persistent mode, you'll need to keep track of the current boss' max HP in a cookie.

**Comment by Nifty255** [comment]
Thanks for bringing this to my attention! While that was admittedly pretty funny to watch, I can definitely see that it was frustrating. The issue should now be resolved.
